### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Organizer21** [sergey-dryabzhinsky/options_per_feed#1]
Hi Sergey, this sounds like an very interesting plugin, though I seem to have an issue. 

Is there a trick to getting it set up? It is not showing up under plugins at glance on an older Tiny Tiny RSS v15.7 and neither on the very latest v19.2.

**Comment by sergey-dryabzhinsky** [comment]
Strange.
May be you need to install php-curl extension and restart apache/php-fpm?

**Comment by sergey-dryabzhinsky** [comment]
![Снимок экрана_2019-07-26_00-02-01](https://user-images.githubusercontent.com/717597/61908772-22999d00-af39-11e9-8975-b88291c809cc.png)
Plugin in my TTRSS plugins dialog

**Comment by Organizer21** [comment]
Hmm, very strange.... curl is running for sure (7.58.0); I'll have another look... thanks.

**Comment by Organizer21** [comment]
FYI Solved this by renaming the folder to the same as the class name "options_per_feed" as I originally had just copied it as supplied "options_per_feed-1.4.0".

**Comment by Organizer21** [comment]
By the way how server resource heavy do you feel the plugin is; I'm having about 3000 feeds checks every 30 minutes and not sure how much overhead this would cause if used to fix maybe issues with only 10 or 20 of those 3000. Any thoughts?

And in the case of a af_readability trigger to try to inline the full text for an article, would the plugin also be hooked in still or would that not work in that case?

**Comment by sergey-dryabzhinsky** [comment]
As I understand TTRSS API - plugin will be triggered only for feed download.
And not for article text.
